### ISSUE TITLE
Binder can't find pandas

### ISSUE THREAD

**Issue by jkhales** [AkshajD/Epigenetic-Clock#1]
<img width="943" alt="Screen Shot 2021-03-27 at 3 36 17 pm" src="https://user-images.githubusercontent.com/1220444/112732761-42554580-8f12-11eb-8a09-7e864bd2d598.png">

**Comment by AkshajD** [comment]
Forgot to respond to this (sorry about that), but it should be fixed now. Just needed to add in a file to let the Binder program know to import all the dependencies beforehand.
